config/routes.rb
Rails.application.routes.draw do
  root to: "cookings#timer"
  get 'cookings/:id/timer/recipes/:recipe_id', to: 'recipes#show', as: 'timer_id_recipe'
  get 'cookings/timer', to: 'cookings#timer', as: 'timer'


  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :cookings do
    member do
      get 'timer_id'      
    end
    collection do
      get 'search'
    end
  end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :recipes
  validates :cooking_material, presence: true, length:  { maximum: 30 }
  validates :cooking_name, presence: true, length:  { maximum: 30 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :cookings
  has_many :recipe_materials
  has_many :recipe_procedures
  has_one_attached :image

  validates :recipe_name, presence: true, length:  { maximum: 30 }
  validates :recipe_time, presence: true, numericality: { only_integer: true }
end

app/models/recipe_material.rb
class RecipeMaterial < ApplicationRecord
  belongs_to :recipe

  validates :material, presence: true, length:  { maximum: 30 }
  validates :quantity, presence: true, length:  { maximum: 30 }
end

app/models/recipe_procedure.rb
class RecipeProcedure < ApplicationRecord
  belongs_to :recipe

  validates :procedure, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  validates :password, length: { minimum: 6 ,maximum: 255}

  has_and_belongs_to_many :cookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  before_action :set_cooking, only: %i[ show edit update destroy timer_id]
  skip_before_action :login_required

  # GET /cookings or /cookings.json
  def index
    Cooking.where(hour: nil).update_all(hour: 0)
    Cooking.where(minute: nil).update_all(minute: 0)
    Cooking.where(second: nil).update_all(second: 0)
    if logged_in?
      @q = Cooking.left_outer_joins(:users).where(cookings_users:{user_id: current_user.id}).ransack(params[:q])
      @cookings = @q.result(distinct: true).page(params[:page])
    else
      @q = Cooking.left_outer_joins(:users).where(cookings_users:{user_id: nil}).ransack(params[:q])
      @cookings = @q.result(distinct: true).page(params[:page])
    end
  end

  # GET /cookings/1 or /cookings/1.json
  def show
  end

  # GET /cookings/new
  def new
    @cooking = Cooking.new
  end

  # GET /cookings/1/edit
  def edit
  end

  # POST /cookings or /cookings.json
  def create
    @user = current_user
    @cooking = current_user.cookings.new(cooking_params)
    if @cooking.save
      @user.cookings << @cooking
      redirect_to cookings_path(current_user.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cookings/1 or /cookings/1.json
  def update
    respond_to do |format|
      if @cooking.update(cooking_params)
        format.html { redirect_to cookings_url, notice: "タイマーを更新しました" }
        format.json { render :show, status: :ok, location: @cooking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookings/1 or /cookings/1.json
  def destroy
    @cooking.destroy

    respond_to do |format|
      format.html { redirect_to cookings_url, notice: "タイマーを消去しました。" }
      format.json { head :no_content }
    end
  end

  def timer
  end

  def timer_id
    @recipes = Recipe.where("recipe_time < ? ", @cooking.minute+@cooking.hour*60).order("RANDOM()").limit(3)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooking
      @cooking = Cooking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cooking_params
      params.require(:cooking).permit(:cooking_material, :cooking_name, :hour, :minute, :second, :user_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def show
    @recipe = Recipe.find_by(id: :recipe_id)
  end

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[recipe.id])
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe = Recipe.find(params[recipe.id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[recipe.id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:recipe_name, :recipe_time, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create] 

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      flash[:notice] = 'ログインしました'
      redirect_to timer_path(user.id)
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードに誤りがあります'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to timer_path(@user.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      log_in(@user)
      flash[:notice] = 'アカウントを更新しました' 
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to current_user unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/timer_helper.rb
module TimerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cookings/_form.html.erb
<%= form_with(model: cooking, local: true) do |form| %>
  <% if cooking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cooking.errors.count, "error") %> prohibited this cooking from being saved:</h2>

      <ul>
        <% cooking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
    <tbody>
      <tr>
      <div class="field">
        <td><%= form.label :材料 %></td>
        <td><%= form.text_field :cooking_material %></td>
      </div>
      </tr>
      <tr>
      <div class="field">
        <td><%= form.label :調理工程 %></td>
        <td><%= form.text_field :cooking_name %></td>
      </div>
      </tr>
      <tr>
      <div class="field">
        <td><%= form.label :時 %></td>
        <td><%= form.number_field :hour, min: 0, max: 23 %></td>
      </div>
      </tr>
      <tr>
      <div class="field">
        <td><%= form.label :分 %></td>
        <td><%= form.number_field :minute, min: 0, max: 59 %></td>
      </div>
      </tr>
      <tr>
      <div class="field">
        <td><%= form.label :秒 %></td>
        <td><%= form.number_field :second, min: 0, max: 59 %></td>
      </div>
      </tr>
    </tboby>
  </table>

  <div class = "button">
  <div class="actions">
    <%= form.submit "登録" %>
  </div>
<% end %>

app/views/cookings/edit.html.erb
<section class="section">
  <div class= "section_inner">
    <h1>タイマー編集</h1>

    <%= render 'form', cooking: @cooking %>
    <div id = "back">
      <%= link_to '戻る', cookings_path %>
    </div>

  </div>
</section>

app/views/cookings/index.html.erb
<section class="section">
<div class = "section_inner">
  <div class= "title">
    <h1>タイマー一覧</h1>
  </div>

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>   

  <%= search_form_for @q do |f| %>
    <div class="search">
    <table>
      <tbody>
        <tr>
          <td><%= f.label :cooking_material_or_cooking_name_cont, 'キーワード' %></td>
          <td><%= f.search_field :cooking_material_or_cooking_name_cont %></td>
        </tr>
      </tbody>
    </table>  
    <%= f.submit '検索' %>
    </div>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>材料</th>
        <th>調理工程</th>
        <th colspan="5">時間</th>
        <th>タイマーセット</th>
        <% if logged_in? %>
          <th>編集</th>
          <th>削除</th>    
        <% end %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cookings.each do |cooking| %>
        <tr>
          <td><%= cooking.cooking_material %></td>
          <td><%= cooking.cooking_name %></td>
          <td><%= cooking.hour %></td>
          <td><%= ":" %></td>
          <td>
            <% if cooking.minute <10 %>
              <%= "0" + cooking.minute.to_s %>
            <% else %>
              <%= cooking.minute %>
            <% end %>
            </td>
          <td><%= ":" %></td>
          <td>
            <% if cooking.second <10 %>
              <%= "0" + cooking.second.to_s %>
            <% else %>
              <%= cooking.second %>
            <% end %>
          </td>
          <td><%= link_to 'タイマーセット', timer_id_cooking_path(cooking) %></td>
          <% if logged_in? %>        
            <td><%= link_to '編集', edit_cooking_path(cooking) %></td>
            <td><%= link_to '削除', cooking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @cookings %>

  <br>

  <% if logged_in? %>
    <%= link_to '新規登録', new_cooking_path %>
  <% end %>
  </div>
</section>

app/views/cookings/new.html.erb
<section class="section">
  <div class= "section_inner">
  <div class= "title">
    <h1>タイマー登録</h1>
  </div>

    <%= render 'form', cooking: @cooking %>
  </div>
</seciton>

app/views/cookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cooking material:</strong>
  <%= @cooking.cooking_material %>
</p>

<p>
  <strong>Cooking name:</strong>
  <%= @cooking.cooking_name %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @cooking.cooking_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @cooking.user_id %>
</p>

<%= link_to 'Edit', edit_cooking_path(@cooking) %> |
<%= link_to 'Back', cookings_path %>

app/views/cookings/timer.html.erb
<div class = "message">
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>   
</div>

<section class="section">
<form name="timer" id="timer">
<div class = "number">
<input type="number" value="0" min=0 max=24>:
<input type="number" value="0" min=0 max=59>:
<input type="number" value="0" min=0 max=59><br>
</div>
<div class = "timer_button">
<input type="button" value="start" onclick="cntStart()">
<input type="button" value="stop" onclick="cntStop()">
<input type="button" value="reset" id="reset" onclick="reSet()">
</div>
</form>
</section>

<div class= "space">
</div>

<script>
var timer1;


//カウントダウン関数を1000ミリ秒毎に呼び出す関数
function cntStart()
{
  document.timer.elements[3].disabled=true;
  timer1=setInterval("countDown()",1000);
}

//タイマー停止関数
function cntStop()
{
  document.timer.elements[3].disabled=false;
  clearInterval(timer1);
}

//カウントダウン関数
function countDown()
{
  var hour=document.timer.elements[0].value;
  var min=document.timer.elements[1].value;
  var sec=document.timer.elements[2].value;
  
    if (hour=="") hour=0;
      hour=parseInt(hour);
    
    if (min=="") min=0;
    min=parseInt(min);
    
    if (sec=="") sec=0;
    sec=parseInt(sec);
    
    tmWrite(hour*3600+min*60+sec-1);
  
}

//残り時間を書き出す関数
function tmWrite(int)
{
  int=parseInt(int);
  
  if (int<=0)
  {
    reSet();
    alert("時間です！");
  }
  else
  {
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[0].value= Math.floor(int / 3600);
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[1].value=Math.floor(int % 3600 / 60);
    //残り秒数はintを60で割った余り
    document.timer.elements[2].value=int % 3600 % 60;
  }
}

//フォームを初期状態に戻す（リセット）関数
function reSet()
{
  document.timer.elements[0].value="0";
  document.timer.elements[1].value="0";
  document.timer.elements[2].value="0";
  document.timer.elements[3].disabled=false;
  clearInterval(timer1);
} 
</script>

app/views/cookings/timer_id.html.erb
<section class="section">
  <form name="timer" id="timer_id">
    <div class = "number">
      <input type="number" value=<%= @cooking.hour %> min=0 max=24 %>:
      <input type="number" value=<%= @cooking.minute %> min=0 max=59>:
      <input type="number" value=<%= @cooking.second %> min=0 max=59><br>
    </div>
    <div class = "timer_button">
      <input type="button" value="start" id= "start" onclick="cntStart()">
      <input type="button" value="stop" onclick="cntStop()">
      <input type="button" value="reset" id="reset" onclick="reSet()">
    </div>
  </form>

  <div id="recipe_area">
    <%= render partial: 'recipes/show', locals: { cooking: @cooking, recipes: @recipes } %>
  </div>
</section>

<script>

var timer1;

//カウントダウン関数を1000ミリ秒毎に呼び出す関数
function cntStart()
{
  document.timer.elements[3].disabled=true;
  timer1=setInterval("countDown()",1000);
}

//タイマー停止関数
function cntStop()
{
  document.timer.elements[3].disabled=false;
  clearInterval(timer1);
}

//カウントダウン関数
function countDown()
{
  var hour=document.timer.elements[0].value;
  var min=document.timer.elements[1].value;
  var sec=document.timer.elements[2].value;
  
    if (hour=="") hour=0;
      hour=parseInt(hour);
    
    if (min=="") min=0;
    min=parseInt(min);
    
    if (sec=="") sec=0;
    sec=parseInt(sec);
    
    tmWrite(hour*3600+min*60+sec-1);
  
}

//残り時間を書き出す関数
function tmWrite(int)
{
  int=parseInt(int);
  
  if (int<=0)
  {
    reSet();
    alert("時間です！");
  }
  else
  {
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[0].value= Math.floor(int / 3600);
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[1].value=Math.floor(int % 3600 / 60);
    //残り秒数はintを60で割った余り
    document.timer.elements[2].value=int % 3600 % 60;
  }
}

//フォームを初期状態に戻す（リセット）関数
function reSet()
{
  document.timer.elements[0].value=<%= @cooking.hour %>;
  document.timer.elements[1].value=<%= @cooking.minute %>;
  document.timer.elements[2].value=<%= @cooking.second %>;
  document.timer.elements[3].disabled=false;
  clearInterval(timer1);
} 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <hearder>
      <div class = "header">
        <div class = "log">
          <h3>Cooking Time</h3>
        </div>
        <ul class = "nav">
          <% if logged_in? %>
            <div class = "nav_item">
              <li><%= link_to "タイマー", timer_path(current_user.id) %></li>
            </div>
            <div class = "nav_item">
              <li><%= link_to "タイマー一覧", cookings_path(current_user.id) %></li>
            </div>
            <div class = "nav_item">
              <li><%= link_to "アカウント", user_path(current_user.id) %></li>
            </div>
            <div class = "nav_item">
              <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            </div>
          <% else %>
            <div class = "nav_item">
              <li><%= link_to "タイマー", timer_path %></li>
            </div>
            <div class = "nav_item">
              <li><%= link_to "タイマー一覧", cookings_path %></li>
            </div>
            <div class = "nav_item">
              <li><%= link_to "アカウント登録", new_user_path %></li>
            </div>
            <div class = "nav_item">
              <li><%= link_to "ログイン", new_session_path %></li>
            </div>
          <% end %>
        </ul>
      </div>
    </header>

    <%= yield %>
    
    <footer>
      <nav>
        <ul class = "footer_item">
          <% if logged_in? %>
            <div class = "footer_nav_item">
              <li><%= link_to "タイマー", timer_path(current_user.id) %></li>
            </div>
            <div class = "footer_nav_item">
              <li><%= link_to "タイマー一覧", cookings_path(current_user.id) %></li>
            </div>
          <% else %>
            <div class = "footer_nav_item">
              <li><%= link_to "タイマー", timer_path %></li>
            </div>
            <div class = "footer_nav_item">
              <li><%= link_to "タイマー一覧", cookings_path %></li> 
            </div>
          <% end %>
          <div class = "footer_nav_item">
            <li><h4>Cooking Time</h4></li>
          </div>
        </ul>
        <p class ="footer_copy">©haga ryota</p>
      </nav>
    </footer>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_name %>
    <%= form.text_field :recipe_name %>
  </div>

  <div class="field">
    <%= form.label :recipe_time %>
    <%= form.number_field :recipe_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_home.html.erb
home

app/views/recipes/_show.html.erb
<h2><%= cooking.hour*60 + cooking.minute %>分で作れるレシピ</h2>
<% unless recipes.empty? %>
  <div class = "recipe">
        <% recipes.each do |recipe| %>
          <div class = "base-image">
            <div class = "base">
              <h3 class="recipe_name"><%= recipe.recipe_name %></h3>
              時間：<%= recipe.recipe_time %>分
              <div class = "material">
                材料：
                <% recipe.recipe_materials.each do |recipe_material| %>
                  <table>
                    <tr>
                      <td><%= recipe_material.material %></td>
                      <td><%= recipe_material.quantity %></td>
                    </tr>
                  </table>
                <% end %>
              </div>
            </div>
            <% if recipe.image.attached? %>
              <%= image_tag recipe.image,class: "recipe_img" %>
            <% end %>
          </div>
          <div class = "content">
            ＜料理手順＞
            <% recipe.recipe_procedures.each_with_index do |recipe_procedure,i| %>
              <ul>  
              <li><%= i+1 %>. <%= recipe_procedure.procedure %><li>
              </ul>
            <% end %>
          </div>
        <% end %>
  </div>
  <% else %>
    <%= "レシピがありません" %>
  <% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Recipe name</th>
      <th>Recipe time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.recipe_name %></td>
        <td><%= recipe.recipe_time %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/recipe.js.erb
$("#recipe_area").html("<%= j(render 'recipes/recipe', { recipe: @recipe }) %>")

app/views/recipes/show.js.erb
$("#recipe_area").html("<%= j(render 'recipes/show', {recipes: @recipes, recipe: @recipe }) %>")

app/views/users/edit.html.erb
<section class="section">
<div class="section_inner">
  <div class= "title">
    <h1>アカウント編集</h1>
  </div>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_with(model: @user, local: true) do |f| %>
      <table>
        <tbody>
          <tr>
            <td><%= f.label :名前 %></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label :メールアドレス %></td>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <td><%= f.label :パスワード %></td>
            <td><%= f.password_field :password %></td>
          </tr>
          <tr>
            <td><%= f.label :パスワード（確認） %></td>
            <td><%= f.password_field :password_confirmation %></td>
          </tr>
        </tbody>
      </table>
      <div class = "button">
      <%= f.submit "更新" %>
    <% end %>
    <div id = "back">
      <%= link_to "戻る", user_path %>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="section">
<div class ="section_inner">
  <div class= "sign_in">
    <div class= "title">
      <h1>アカウント登録</h1>
    </div>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <%= form_with(model: @user, local: true) do |f| %>
        <table>
          <tbody>
            <tr>
              <td><%= f.label :名前 %></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= f.label :メールアドレス %></td>
              <td><%= f.email_field :email %></td>
            </tr>
            <tr>
              <td><%= f.label :パスワード %></td>
              <td><%= f.password_field :password %></td>
            </tr>
            <tr>
              <td><%= f.label :パスワード（確認） %></td>
              <td><%= f.password_field :password_confirmation %></td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "新規登録" %>
      <% end %>
  </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
<div class="section_inner">
  <div class= "title">
    <h1>アカウント詳細</h1>
  </div>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>   

    <table>
      <tbody>
        <tr>
          <td>名前</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
      <tbody>
    </table>
    <div id = "edit-user">
      <%= link_to "編集", edit_user_path %>
    </div>
  </div>
</section>